/**
 * Embed the env daemon bundle (scripts/embed-env-bundle.ts): reads
 * `packages/env/dist/entry.bundle.js` (built by `pnpm build` in the env
 * package) and writes `src/generated/env-bundle.ts` — a base64 literal
 * the hub DO embeds into its Box-provisioning uploads.
 *
 * Run after building the env package:
 *
 *   pnpm --filter @saku/env build
 *   pnpm --filter @saku/deploy embed:env-bundle
 */

import path from "node:path";
import { Effect, FileSystem } from "effect";
import { NodeFileSystem } from "@effect/platform-node";

const here = import.meta.dirname;
const root = path.resolve(here, "..");
const bundlePath = path.join(root, "..", "env", "dist", "entry.bundle.js");
const outPath = path.join(root, "src", "generated", "env-bundle.ts");

await Effect.runPromise(
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const bundle = yield* fs.readFileString(bundlePath);
    const encoded = Buffer.from(bundle, "utf-8").toString("base64");

    const out = `/**
 * Generated by scripts/embed-env-bundle.ts — do not edit.
 * The env daemon bundle (packages/env/dist/entry.bundle.js), base64, for
 * the hub DO's Box provisioning (the DO cannot read the filesystem).
 */
export const ENV_BUNDLE_BASE64 = ${JSON.stringify(encoded)};
`;

    yield* fs.makeDirectory(path.dirname(outPath), { recursive: true });
    yield* fs.writeFileString(outPath, out);
    yield* Effect.logInfo(`embedded ${bundle.length} bytes -> ${outPath}`);
  }).pipe(Effect.provide(NodeFileSystem.layer)),
);
