/**
 * Embed the env daemon bundle (scripts/embed-env-bundle.ts): reads
 * `packages/env/dist/entry.bundle.js` (built by `pnpm build` in the env
 * package) and writes `src/generated/env-bundle.ts` — a base64 literal
 * the hub DO embeds into its Box-provisioning uploads.
 *
 * Run after building the env package:
 *
 *   pnpm --filter @saku/env build
 *   pnpm --filter @saku/deploy embed:env-bundle
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Effect } from "effect";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const bundlePath = join(root, "..", "env", "dist", "entry.bundle.js");
const outPath = join(root, "src", "generated", "env-bundle.ts");

const bundle = await readFile(bundlePath, "utf8");
const encoded = Buffer.from(bundle, "utf8").toString("base64");

const out = `/**
 * Generated by scripts/embed-env-bundle.ts — do not edit.
 * The env daemon bundle (packages/env/dist/entry.bundle.js), base64, for
 * the hub DO's Box provisioning (the DO cannot read the filesystem).
 */
export const ENV_BUNDLE_BASE64 = ${JSON.stringify(encoded)};
`;

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, out);
await Effect.runPromise(Effect.logInfo(`embedded ${bundle.length} bytes -> ${outPath}`));
